# Generated by Django 4.2.4 on 2023-09-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComicsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(default='media/avatars/undefined.jpg', upload_to='avatars'),
        ),
    ]
