# Generated by Django 4.2.3 on 2023-09-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComicsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='role',
        ),
    ]
