# Generated by Django 4.2.4 on 2023-09-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComicsApp', '0002_alter_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(upload_to='avatars'),
        ),
    ]
